app/views.py
"""This module supplies with view blueprint. It allows to make up general routs instead of
typical :func:`app.route` in order to work with application factory properly"""
from typing import Tuple

from flask import Blueprint
from flask import render_template
from werkzeug.exceptions import NotFound

from . import logger

view = Blueprint('view', __name__)


@view.route('/')
def index() -> str:
    """
    Handles start page.
    """
    return render_template('index.html')


@view.app_errorhandler(NotFound)
def page_not_found(error: NotFound) -> Tuple[str, int]:
    """
    Handles 404 error.
    """
    logger.info('404 error was raised')
    return render_template('404.html'), error.code

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block extra_head %}{% endblock %}
</head>
<body>
{% block body %}
    <div class="wrapper">
        <div class="content">
            {% block flashes %}
                <dir class="flashes">
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endwith %}
                </dir>
            {% endblock %}
            <div class="content__header">
                <div class="content__header_wrapper">
                    <a href="{{ url_for('view.index') }}">
                        <div onclick="document.location = ''" class="content__title">Welcome to Flask simple chats!
                        </div>
                    </a>
                    <div class="content__navbar">
                        {% if user %}
                            <button class="content__login"
                                    onclick="document.location = '{{ url_for('chats.list') }}'">My chats
                            </button>
                            <button onclick="document.location = '{{ url_for('authentication.logout') }}'"
                                    class="content__register">Log out
                            </button>
                        {% else %}
                            <button class="content__login"
                                    onclick="document.location = '{{ url_for('authentication.login') }}'">Log in
                            </button>
                            <button onclick="document.location = '{{ url_for('authentication.register') }}'"
                                    class="content__register">Sign in
                            </button>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="content__article">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <footer>
            <div class="footer__container">
                <div class="footer__info">
                    <p>SUPPORT CENTER:</p>
                    <p><a style="color: black;" href="mailto:duma12let@gmail.com">duma12let@gmail.com</a>
                    </p>
                    <p><a style="color: black;" href="https://www.instagram.com/_d.i.m.o.n.c.h.i.k__/">Instagram</a></p>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block title %}Simple chats{% endblock %}
{% block content %}
    <div class="content__main">
        <div class="content__buttons">
            <div onclick="document.location = '{{ url_for('chats.search') }}'" class="content__button">Begin simple chat</div>
{#            <div class="content__button">Begin encrypted chat</div>#}
        </div>
    </div>
{% endblock %}